import { Component, OnInit, signal, computed, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PuzzleService } from './core/services/puzzle';
import { Difficulty, TopicItem } from './core/models/puzzle.model';

interface CellCoords {
  row: number;
  col: number;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.html',
  styleUrl: './app.scss',
})
export class App implements OnInit {
  // Application State State Management via Signals
  protected readonly title = signal('Word Search Puzzle');
  protected readonly topics = signal<TopicItem[]>([
    { id: 'pokemon', name: 'Pokémon',
      imageUrl: 'https://vofoegntfdlyoqiloqwz.supabase.co/storage/v1/object/public/puzzle-images/pokemon_card.PNG' },
    { id: 'friends', name: 'Friends',
      imageUrl: 'https://vofoegntfdlyoqiloqwz.supabase.co/storage/v1/object/public/puzzle-images/friends_card.PNG' },
    { id: 'animals', name: 'Animals',
      imageUrl: 'https://vofoegntfdlyoqiloqwz.supabase.co/storage/v1/object/public/puzzle-images/default_card.PNG' },
  ]);

  protected readonly selectedTopic = signal<string>('pokemon');
  protected readonly selectedDifficulty = signal<Difficulty>('EASY');
  
  // Game Matrix and Words State
  protected readonly grid = signal<string[][]>([]);
  protected readonly targetWords = signal<string[]>([]);
  protected readonly foundWords = signal<Set<string>>(new Set());
  
  // User Selection Interaction Tracking State
  protected readonly isSelecting = signal<boolean>(false);
  protected readonly selectionStart = signal<CellCoords | null>(null);
  protected readonly selectionCurrent = signal<CellCoords | null>(null);

  // Computes the words remaining to find dynamically
  protected readonly remainingCount = computed(() => {
    return this.targetWords().length - this.foundWords().size;
  });

  constructor(private puzzleService: PuzzleService) {
    // Automatically re-fetch data whenever configuration triggers change
    effect(() => {
      this.loadNewPuzzle(this.selectedTopic(), this.selectedDifficulty());
    });
  }

  ngOnInit(): void {}

  protected loadNewPuzzle(topic: string, difficulty: Difficulty): void {
    this.puzzleService.generatePuzzle(topic, difficulty).subscribe({
      next: (response) => {
        this.grid.set(response.grid);
        this.targetWords.set(response.words);
        this.foundWords.set(new Set());
        this.clearSelection();
      },
      error: (err) => console.error('Failed to resolve matrix composition stream:', err)
    });
  }

  protected selectTopic(topicId: string): void {
    this.selectedTopic.set(topicId);
  }

  protected changeDifficulty(event: Event): void {
    const element = event.target as HTMLSelectElement;
    this.selectedDifficulty.set(element.value as Difficulty);
  }

  // --- Interaction Mechanics Matrix Event Handlers ---

  protected onCellMouseDown(row: number, col: number): void {
    this.isSelecting.set(true);
    this.selectionStart.set({ row, col });
    this.selectionCurrent.set({ row, col });
  }

  protected onCellMouseEnter(row: number, col: number): void {
    if (!this.isSelecting()) return;
    this.selectionCurrent.set({ row, col });
  }

  protected onMouseUp(): void {
    if (!this.isSelecting()) return;
    this.evaluateCurrentSelection();
    this.isSelecting.set(false);
    this.selectionStart.set(null);
    this.selectionCurrent.set(null);
  }

  private clearSelection(): void {
    this.isSelecting.set(false);
    this.selectionStart.set(null);
    this.selectionCurrent.set(null);
  }

  /**
   * Evaluates the trace path generated by vector points to read string characters 
   */
  private evaluateCurrentSelection(): void {
    const start = this.selectionStart();
    const end = this.selectionCurrent();
    if (!start || !end) return;

    const word = this.extractStringFromPath(start, end);
    const reversedWord = word.split('').reverse().join('');

    if (this.targetWords().includes(word) && !this.foundWords().has(word)) {
      this.markWordAsFound(word);
    } else if (this.targetWords().includes(reversedWord) && !this.foundWords().has(reversedWord)) {
      this.markWordAsFound(reversedWord);
    }
  }

  private extractStringFromPath(start: CellCoords, end: CellCoords): string {
    const dRow = Math.sign(end.row - start.row);
    const dCol = Math.sign(end.col - start.col);
    
    let currRow = start.row;
    let currCol = start.col;
    let extracted = '';

    const steps = Math.max(Math.abs(end.row - start.row), Math.abs(end.col - start.col));

    for (let i = 0; i <= steps; i++) {
      extracted += this.grid()[currRow][currCol];
      currRow += dRow;
      currCol += dCol;
    }
    return extracted;
  }

  private markWordAsFound(word: string): void {
    const updatedSet = new Set(this.foundWords());
    updatedSet.add(word);
    this.foundWords.set(updatedSet);
  }

  /**
   * Evaluation engine checking if an individual cell position lies within the active selection trajectory vector
   */
  protected isCellSelected(row: number, col: number): boolean {
    const start = this.selectionStart();
    const end = this.selectionCurrent();
    if (!start || !end) return false;

    const minR = Math.min(start.row, end.row);
    const maxR = Math.max(start.row, end.row);
    const minC = Math.min(start.col, end.col);
    const maxC = Math.max(start.col, end.col);

    // Validates alignment layout conditions: vertical, horizontal, or perfect diagonal lines
    const isHorizontal = start.row === end.row;
    const isVertical = start.col === end.col;
    const isDiagonal = Math.abs(start.row - end.row) === Math.abs(start.col - end.col);

    if (!isHorizontal && !isVertical && !isDiagonal) return false;

    if (isHorizontal) return row === start.row && col >= minC && col <= maxC;
    if (isVertical) return col === start.col && row >= minR && row <= maxR;
    
    // Diagonal slope track computation verification
    const belongsToBox = row >= minR && row <= maxR && col >= minC && col <= maxC;
    if (belongsToBox) {
      return Math.abs(row - start.row) === Math.abs(col - start.col);
    }

    return false;
  }
}